# Ariel Kohanim
# Project:Time and Forking Children

# This is a Makefile for my lab 1 assignment. It allows me to easily and accurately rebuild
# the lab assignment.

SOURCES = comp322_lab1.c

EXE = time-4-baby-and-me

CFLAGS = -Wall

SRC= comp322_lab1.c
OBJ= comp322_lab1.c

CC=gcc
CFLAGS=-g
